# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

runTest <- function() {
    .Call('RcppNLopt_runTest', PACKAGE = 'RcppNLopt')
}

wrap_nlopt <- function(x0, lb, ub, options, Rofun, Rgrad = NULL, Rineq = NULL, Rgrad_ineq = NULL, Req = NULL, Rgrad_eq = NULL) {
    .Call('RcppNLopt_wrap_nlopt', PACKAGE = 'RcppNLopt', x0, lb, ub, options, Rofun, Rgrad, Rineq, Rgrad_ineq, Req, Rgrad_eq)
}

