// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// runTest
NumericVector runTest();
RcppExport SEXP RcppNLopt_runTest() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    rcpp_result_gen = Rcpp::wrap(runTest());
    return rcpp_result_gen;
END_RCPP
}
// wrap_nlopt
List wrap_nlopt(const NumericVector& x0, const NumericVector& lb, const NumericVector& ub, const List& options, const Function& Rofun, const Nullable<Function>& Rgrad, const Nullable<Function>& Rineq, const Nullable<Function>& Rgrad_ineq, const Nullable<Function>& Req, const Nullable<Function>& Rgrad_eq);
RcppExport SEXP RcppNLopt_wrap_nlopt(SEXP x0SEXP, SEXP lbSEXP, SEXP ubSEXP, SEXP optionsSEXP, SEXP RofunSEXP, SEXP RgradSEXP, SEXP RineqSEXP, SEXP Rgrad_ineqSEXP, SEXP ReqSEXP, SEXP Rgrad_eqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type lb(lbSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type ub(ubSEXP);
    Rcpp::traits::input_parameter< const List& >::type options(optionsSEXP);
    Rcpp::traits::input_parameter< const Function& >::type Rofun(RofunSEXP);
    Rcpp::traits::input_parameter< const Nullable<Function>& >::type Rgrad(RgradSEXP);
    Rcpp::traits::input_parameter< const Nullable<Function>& >::type Rineq(RineqSEXP);
    Rcpp::traits::input_parameter< const Nullable<Function>& >::type Rgrad_ineq(Rgrad_ineqSEXP);
    Rcpp::traits::input_parameter< const Nullable<Function>& >::type Req(ReqSEXP);
    Rcpp::traits::input_parameter< const Nullable<Function>& >::type Rgrad_eq(Rgrad_eqSEXP);
    rcpp_result_gen = Rcpp::wrap(wrap_nlopt(x0, lb, ub, options, Rofun, Rgrad, Rineq, Rgrad_ineq, Req, Rgrad_eq));
    return rcpp_result_gen;
END_RCPP
}
